engines:
  structure:
    enabled: true
  duplication:
    enabled: true
  sonar-java:
    enabled: true
ratings:
  paths:
    - "**.java"
exclude_paths:
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.py"
