---
engines:
  checkstyle:
    enabled: true
    channel: beta
    include_paths:
      - "guava-testlib/"
    config:
      file: checkstyle.xml
ratings:
  paths:
  - "**.java"
exclude_paths:
- "**.js"
- "**.jsx"
- "**.rb"
- "**.py"
- "android/"
- "guava/"
- "guava-gwt/"
- "guava-tests/"
