engines:
  structure:
    enabled: false
  duplication:
    enabled: false
  sonar-java:
    enabled: true
    include_paths:
      "**/*.java"
ratings:
  paths:
    - "**.java"
exclude_paths:
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.py"
